### ISSUE TITLE
Bug Uncaught Error: seems like cookie tossing is happening.

### ISSUE THREAD

**Issue by geekyme** [meteorhacks/fast-render#105]
This seems to be happening on localhost while I was developing. 

My unit tests are running using sanjo:jasmine package. Immediately after installing fast-render, some of my tests stopped running and the console reports the error

```
Uncaught Error: seems like cookie tossing is happening.
```

**Comment by arunoda** [comment]
This is fine.
That happens when you are working on two different apps on the same host.
This is common when you are developing it.

**Comment by geekyme** [comment]
My unit tests stop running completely when that happens.

**Comment by arunoda** [comment]
Hmm. May be we can stop this is happening locally.

**Comment by AnthonyAstige** [comment]
I've suppressed the error throwing for local dev @ https://github.com/AnthonyAstige/fast-render/commit/812d552980756dfe260688fa765bfff84f439279.

I clone my live db to local very often, and every time the error would come up.  Finally got annoyed enough to suppress it.

I'm not sure if the change-set I made is pull request worthy, but it works for me and I've tested briefly.

**Comment by timmyg** [comment]
can this be merged or is there a non code change workaround? It is really slowing development as I am getting this every time a page loads

```
reporters.js?1446131531779:67 Error: seems like cookie tossing is happening. visit here: http://git.io/q4IRHQ
Error: seems like cookie tossing is happening. visit here: http://git.io/q4IRHQ
    at Object.FastRender._securityCheck (http://localhost:65320/packages/meteor:/💻app/packages/meteorhacks_fast-render/packages/meteorhacks_fast-render.js:213:1)
    at Object.FastRender.init (http://localhost:65320/packages/meteor:/💻app/packages/meteorhacks_fast-render/packages/meteorhacks_fast-render.js:157:1)
    at http://localhost:65320/packages/meteor:/💻app/packages/meteorhacks_fast-render/packages/meteorhacks_fast-render.js:507:1
    at http://localhost:65320/packages/meteor:/💻app/packages/meteorhacks_inject-data/packages/meteorhacks_inject-data.js:64:1
    at runStartupCallbacks (http://localhost:65320/packages/meteor:/💻app/packages/meteor/packages/meteor.js:759:1)
    at HTMLDocument.ready (http://localhost:65320/packages/meteor:/💻app/packages/meteor/packages/meteor.js:761:1)

> Before: 8906ms (diff: 8906ms)
    at http://localhost:65320/packages/meteor:/💻app/packages/meteor/packages/meteor.js:765:1
    at http://localhost:65320/packages/meteor:/💻app/packages/meteor/packages/meteor.js:807:1
    at http://localhost:65320/packages/meteor.js?431e407b21bf81d79061795e4fce958bea956e90:1105:4
    at http://localhost:65320/packages/meteor.js?431e407b21bf81d79061795e4fce958bea956e90:1114:3
```

**Comment by StrongBearCeo** [comment]
This happens to me on 2.16.0 but does not on 2.12.0
