### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by SachaG** [meteorhacks/fast-render#90]
I just ran into this when doing `mup reconfig` on a Telescope instance:

```
72.14.186.212] URIError: URI malformed
    at decodeURI (native)
    at Object._pathMatch (packages/meteorhacks:fast-render/lib/server/utils.js:35)
    at Object._processRoutes (packages/meteorhacks:fast-render/lib/server/fast_render.js:28)
    at Object.RouteController [as handle] (packages/meteorhacks:fast-render/lib/server/inject.js:90)
    at next (/opt/meteor/app/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at Object.cookieParser [as handle] (/opt/meteor/app/programs/server/npm/meteorhacks:fast-render/node_modules/connect/lib/middleware/cookieParser.js:65:5)
    at next (/opt/meteor/app/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at Object.Package [as handle] (packages/spiderable/spiderable_server.js:127)
    at next (/opt/meteor/app/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at middleware (packages/oauth/oauth_server.js:157)
```

I don't think it's affecting anything, but I just thought I'd make a note of it :)

**Comment by arunoda** [comment]
Sacha,

If you get this another time, try to copy the HTML content on the view
source and send that as well.

Then I can find the issue.

BTW: I released a new version of FR with a fix for a this kind of error.
Try to update.

**Comment by SachaG** [comment]
OK, I'll do that, and I'll update as well :)

**Comment by arunoda** [comment]
Okay.
