### ISSUE TITLE
fast-render throws an expection when a route's waitOn issues a redirect

### ISSUE THREAD

**Issue by jfly** [meteorhacks/fast-render#91]
When using this.redirect(...) or Router.go(...) in a waitOn, I see either

```
W20150114-16:35:52.889(-8)? (STDERR) error on fast-rendering path: /USNationals2014/results/666 ; error: TypeError: Object [object Object] has no method 'redirect'
```

or

```
W20150114-16:38:11.109(-8)? (STDERR) error on fast-rendering path: /USNationals2014/results/666 ; error: TypeError: Object function router(req, res, next) {                                                          // 13
W20150114-16:38:11.111(-8)? (STDERR)     //XXX this assumes no other routers on the parent stack which we should probably fix      // 14
W20150114-16:38:11.111(-8)? (STDERR)     router.dispatch(req.url, {                                                                // 15
W20150114-16:38:11.111(-8)? (STDERR)       request: req,                                                                           // 16
W20150114-16:38:11.112(-8)? (STDERR)       response: res                                                                           // 17
W20150114-16:38:11.112(-8)? (STDERR)     }, next);                                                                                 // 18
W20150114-16:38:11.112(-8)? (STDERR)   } has no method 'go'
W20150114-16:38:11.112(-8)? (STDERR)     at [object Object].ViewCompetitionController.extend.waitOn (app/both/routes.js:203:14)
W20150114-16:38:11.112(-8)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/iron_router_support.js:99:1
W20150114-16:38:11.113(-8)? (STDERR)     at Array.forEach (native)
W20150114-16:38:11.113(-8)? (STDERR)     at Context.onRoute (packages/meteorhacks:fast-render/lib/server/iron_router_support.js:97:1)
W20150114-16:38:11.113(-8)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/fast_render.js:45:1
```

**Comment by arunoda** [comment]
You can't use these client only methods like this in server. So, you need to guard them to run only inside the client.
See: https://github.com/meteorhacks/fast-render#3-waiton-and-subscriptions-methods

**Comment by jfly** [comment]
Ah, ok! I actually was able to get things working by putting the redirect in my data method instead.

**Comment by arunoda** [comment]
great. so we are good here :)
